### PR TITLE
Fix path issues with source maps

### LINKED ISSUE #95: Wrong paths in source maps
Please consider this simple demo configuration: https://github.com/thorn0/grunt-contrib-concat-sourcemaps-bug

After compiling TypeScript, we have this structure:
```
src
|   bar.ts
|
\---foodir
        foo.ts
build
|
\---src
    |   bar.js
    |   bar.js.map       -- correctly refers to ../../src/bar.ts`
    |
    \---foodir
            foo.js
            foo.js.map  -- correctly refers to ../../../src/foodir/foo.ts
```
But after concatenation, we get `build/foobar.js.map`, which has the following contents in its `sources` field: `["../src/bar.ts","../../src/foodir/foo.ts"]`, while it should be `["../src/bar.ts","../src/foodir/foo.ts"]`.

Also, README [states](https://github.com/gruntjs/grunt-contrib-concat#sourcemapstyle) that the default value for the `sourceMapStyle` option is `embed`, so I expected to find the TypeScript sources inside of `foobar.js.map`, but it's not there.

### PR DESCRIPTION
**Pull request by RiaanN**
On Windows, node's path api returns backslashes for path separators.

Because the source-map library expects forward slashes in all cases, their relative path logic (specifically their "normalize" function) gives incorrect results when passing in backslash.  The mozilla/source-map library won't change this, because they are actually expecting URLs as input - see https://github.com/mozilla/source-map/issues/91#issuecomment-34845169.

This fix is similar to the one made for grunt-contrib-uglify: https://github.com/gruntjs/grunt-contrib-uglify/pull/175.

Fixes #95.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@vladikoff: can you add Appveyor properly? This is supposed to fix the Windows issue yet we can't check automatically.

File: tasks/lib/sourcemap.js [hunk 1]
```diff
@@ -121,6 +121,9 @@ exports.init = function(grunt) {
       // Consider the relative path from source files to new sourcemap.
       var sourcePathToSourceMapPath =
         path.relative(path.dirname(this.dest), path.dirname(sourceMapPath));
+      // sourceMap path references are URLs, so ensure forward slashes are used for paths passed to sourcemap library
```
Comment (XhmikosR) [inline tasks/lib/sourcemap.js]: Indentation is off for this whole added block.

**Comment by XhmikosR** [comment]
@RiaanN: I still get 5 failures, the same failures we get on master https://ci.appveyor.com/project/gruntjs/grunt-contrib-concat/build/job/k0laci6yydq2q5fb

File: tasks/lib/sourcemap.js (hunk 1 above)
Comment (RiaanN) [inline tasks/lib/sourcemap.js]: Apologies, but I'm not seeing the indentation issue in the diff on GitHub or on my side:  the added code is lined up with the surrounding code, and indented by two spaces from the containing if... What am I missing?

Comment (XhmikosR) [inline tasks/lib/sourcemap.js]: You need to use 2 more spaces so that the newly added block is aligned with the previous line.

**Comment by RiaanN** [comment]
@XhmikosR: Thanks, I'll have a look at those tests and report back.

File: tasks/lib/sourcemap.js (hunk 1 above)
Comment (RiaanN) [inline tasks/lib/sourcemap.js]: Would that be line 122 they should like up with?  Line 122 ends with an "=", so I would assume I should not align with line 123 (since line 123 is indented as it's part of the same logical line as line 122).

Comment (XhmikosR) [inline tasks/lib/sourcemap.js]: Forget about it, just leave it as it is and I'll have a look if/when this is merged. The tests are the important part here.

**Comment by RiaanN** [comment]
The unit tests now all pass on my (Windows) machine.  I hope Appveyor agrees! :smiley:

**Comment by XhmikosR** [comment]
@RiaanN: unfortunately, AppVeyor isn't set up properly yet for this repo so we don't have it for PRs. But the tests seem to pass so gj!

PS. Please squash those 2 patches into one.

**Comment by RiaanN** [comment]
I have squashed the commits, and consolidated the commit message.

**Comment by XhmikosR** [comment]
@vladikoff: we really need AppVeyor set up properly so that the PRs are handled too.

/CC @sindresorhus for review too.

Things seem to work fine from my tests so far.

**Comment by vladikoff** [comment]
@XhmikosR fixed!

**Comment by XhmikosR** [comment]
@vladikoff: thanks! Too bad only owners can trigger a new build :/

**Comment by XhmikosR** [comment]
@RiaanN @sindresorhus: how about using https://github.com/sindresorhus/slash?

**Comment by RiaanN** [comment]
Unfortunately, we can't use that library, because it sometimes keeps the
backslashes (with the intention of keeping the path a valid Windows path).
In our case, the path should be turned into a relative URL, so we must
always convert to forward slashes.

Do you agree?

**Comment by sindresorhus** [comment]
Yes, @RiaanN is right.

**Comment by XhmikosR** [comment]
OK, cool. How about this PR itself then @sindresorhus?
